image:
  file: .gitpod.Dockerfile

checkoutLocation: "/ai4finance/FinRL"

additionalRepositories:
  - url: https://github.com/AI4Finance-Foundation/ElegantRL.git
    checkoutLocation: /ai4finance/ElegantRL
  - url: https://github.com/AI4Finance-Foundation/FinRL-Meta.git
    checkoutLocation: /ai4finance/FinRL-Meta

workspaceLocation: ai4finance/FinRL/main.code-workspace

tasks:
  - name: Configure conda & install dependencies
    init: |
      conda create --name ai4finance python=3.9 -y
      conda activate ai4finance
      conda install -c conda-forge ta-lib -y
      pip install -r requirements.txt
  - name: Precommit hooks
    init: |
      pre-commit install

gitConfig:
  core.autocrlf: input

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap # Added Jupyter Keymap
    - ms-toolsai.jupyter-renderers # Added Jupyter Renderers
    - GitHub.copilot-chat
    - GitHub.copilot
    - ms-python.autopep8
    - ms-python.debugpy
    - jojoee.conda-cheatsheet
