image:
  file: .gitpod.Dockerfile

checkoutLocation: "/ai4finance/FinRL"

additionalRepositories:
  - url: https://github.com/AI4Finance-Foundation/ElegantRL.git
    checkoutLocation: /ai4finance/ElegantRL
  - url: https://github.com/AI4Finance-Foundation/FinRL-Meta.git
    checkoutLocation: /ai4finance/FinRL-Meta

workspaceLocation: ai4finance/FinRL/main.code-workspace

tasks:
  - init: |
      conda create --name ai4finance python=3.9 -y
      conda install -c conda-forge ta-lib -y
      conda activate ai4finance
      pip install -r requirements.txt
      pre-commit install

gitConfig:
  core.autocrlf: input

vscode:
  extensions:
    - ms-python.python
    - ms-python.flake8
    - ms-python.debugpy
    - ms-python.autopep8
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-azuretools.vscode-docker
    - GitHub.copilot-chat
    - GitHub.copilot
