image:
  file: .gitpod.Dockerfile

checkoutLocation: "/ai4finance"

additionalRepositories:
  - url: https://github.com/AI4Finance-Foundation/ElegantRL.git
    checkoutLocation: /ElegantRL
  - url: https://github.com/AI4Finance-Foundation/FinRL-Meta.git
    checkoutLocation: /FinRL-Meta
workspaceLocation: main.code-workspace

tasks:
  - name: Configure conda
    init: |
      conda create --name ai4finance python=3.8
      conda activate ai4finance
    command: |
      pip install -r ai4finance/FinRL/requirements.txt

gitConfig:
  core.autocrlf: input
