image:
  file: .gitpod.Dockerfile

checkoutLocation: "/ai4finance/FinRL"

additionalRepositories:
  - url: https://github.com/AI4Finance-Foundation/ElegantRL.git
    checkoutLocation: /ai4finance/ElegantRL
  - url: https://github.com/AI4Finance-Foundation/FinRL-Meta.git
    checkoutLocation: /ai4finance/FinRL-Meta

workspaceLocation: ai4finance/FinRL/main.code-workspace

tasks:
  - name: Configure conda
    init: |
      conda create --name ai4finance python=3.8 -y
      conda activate ai4finance
      conda install -c conda-forge ta-lib -y
    command: |
      pip install -r requirements.txt

gitConfig:
  core.autocrlf: input

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - GitHub.copilot-chat
    - GitHub.copilot
    - ms-python.autopep8
    - ms-python.debugpy
    - jojoee.conda-cheatsheet

  


