image: gitpod/workspace-python-3.7


additionalRepositories:
    - url: https://github.com/AI4Finance-Foundation/ElegantRL.git
      checkoutLocation: /home/gitpod/ElegantRL
    - url: https://github.com/AI4Finance-Foundation/FinRL-Meta.git
      checkoutLocation: /home/gitpod/FinRL-Meta


tasks:
  - init: |
      echo "Setting up the environment..."
      poetry install --with dev


gitConfig:
    core.autocrlf: input