image:
  file: .gitpod.dockerfile

additionalRepositories:
  - url: https://github.com/AI4Finance-Foundation/ElegantRL.git
    checkoutLocation: /ElegantRL
  - url: https://github.com/AI4Finance-Foundation/FinRL-Meta.git
    checkoutLocation: /FinRL-Meta
workspaceLocation: main.code-workspace

# tasks:
#   - init: |
#       pip install -r requirements.txt

gitConfig:
  core.autocrlf: input
